### ISSUE TITLE
Unable to use iframe with single-spa 

### ISSUE THREAD

**Issue by shekp** [ambitus-it/single-spa-iframes#1]
Hello, 

Trying to use this workaround for testing with https://github.com/alocke12992/single-spa-starting-from-scratch
But, after adding test.js as bellow. 

`import * as singleSpaIframes from 'single-spa-iframes';

const iframeLifeCycles = singleSpaIframes({
    baseUrl: 'http://localhost:9090',
    elGetter() {
      return document.getElementById('globalBody');
    }
  });
 
export const bootstrap = iframeLifeCycles.bootstrap;
export const mount = iframeLifeCycles.mount;
export const unmount = iframeLifeCycles.unmount;`

and register app with 

`
import { registerApplication, start } from 'single-spa';

registerApplication('navBar', () => import('./src/navBar/navBar.app.js').then(mod => mod.navBar), () => true);
registerApplication('home', () => import('./src/home/home.app.js'), (location) => location.pathname === "" || location.pathname === "/" || location.pathname.startsWith('/home'));
registerApplication('angularJS', () => import('./src/angularJS/angularJS.app'), pathPrefix('/angularJS'));
registerApplication('test', () => import('./src/iframe/iframe-test.js'), pathPrefix('/test'));

start();

function pathPrefix(prefix) {
  return function (location) {
    return location.pathname.startsWith(`${prefix}`);
  }
}
`

I have faced with 

single-spa.js:1 Uncaught TypeError: 'test' died in status LOADING_SOURCE_CODE: single_spa_iframes__WEBPACK_IMPORTED_MODULE_0__ is not a function
    at Module../src/iframe/iframe-test.js (iframe-test.js:3)
    at __webpack_require__ (bootstrap:63)

Could plz help, what's is wrong.

**Comment by BrunoBNascimento** [comment]
Why are you importing like this `import * as singleSpaIframes from 'single-spa-iframes';`?

Why not just `import singleSpaIframes from 'single-spa-iframes';`

**Comment by BrunoBNascimento** [comment]
Tested here, just import default.

**Comment by shekp** [comment]
Thank you for help! It's work!
